### ISSUE TITLE
Intel conda channel is not available anymore

### ISSUE THREAD

**Issue by baltruke** [docking-org/zinc22-3d#1]
Hello,

Just wanted to note that intel conda channel is not available anymore (since summer 2024 approximately).

There is potentially a workaround:
conda config --add channels https://software.repos.intel.com/python/conda/
conda install mkl-static mkl-include
And omitting the intel channel name.

However, at least in my case it produced incompatibility not allowing for creating conda environment. 

If you can help anyhow, that would be great.

Cheers,
Hanna

**Comment by jir322** [comment]
Thank you for bringing this to our attention. We will investigate!
